name: Build Eleventy

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      
      - name: Build Site
        run: pnpm run build

      - name: Store Site
        uses: actions/upload-artifact@v3
        with:
          name: urban-geodata-website
          path: |
            _site